language: node_js
node_js: node
before_install:
  - openssl aes-256-cbc -K $encrypted_8e2dd55f8485_key -iv $encrypted_8e2dd55f8485_iv -in deploy_key.enc -out deploy_key -d
  - npm install -g bower
install: npm install
script: npm run bundle
deploy:
  provider: releases
  file_glob: true
  file: dist/*
  skip_cleanup: true
  on:
    repo: openHPI/videoplayer
    branch: releases
